"""
formatter node — produces the final marked-up output.

Brief §5: "Final output includes a rationale for every accepted change."

The output is a single Markdown string that contains:
  - Executive summary (status, iterations, jurisdiction, risk)
  - Per-iteration timeline (so the panel can see the loop worked)
  - Final contract text
  - Redline rationale table
  - Critic coverage map
"""

from __future__ import annotations
from datetime import datetime
from typing import Any

from state import GraphState


def _status_badge(state: GraphState) -> str:
    if state.approved:
        return "✅ APPROVED"
    if state.iteration >= state.max_iterations:
        return "⚠️  MAX ITERATIONS — partner review required"
    return "⏸  IN PROGRESS"


def _coverage_table(state: GraphState) -> str:
    if not state.critic_verdict or not state.critic_verdict.coverage:
        return "_No coverage data._"
    rows = ["| Category | Coverage |", "|----------|----------|"]
    for cat, ok in sorted(state.critic_verdict.coverage.items()):
        rows.append(f"| {cat} | {'✅' if ok else '❌'} |")
    return "\n".join(rows)


def _redline_table(state: GraphState) -> str:
    if not state.redlines:
        return "_No redlines proposed._"
    rows = [
        "| # | Clause | Category | Severity | Change | Rationale |",
        "|---|--------|----------|----------|--------|-----------|",
    ]
    for i, r in enumerate(state.redlines, 1):
        change_summary = r.change_type.title()
        if r.change_type == "REPLACE":
            short_orig = (r.original_text[:50] + "…") if len(r.original_text) > 50 else r.original_text
            short_new = (r.proposed_text[:50] + "…") if len(r.proposed_text) > 50 else r.proposed_text
            change_summary = f"{short_orig} → {short_new}"
        elif r.change_type == "INSERT":
            short_new = (r.proposed_text[:80] + "…") if len(r.proposed_text) > 80 else r.proposed_text
            change_summary = f"INSERT: {short_new}"
        elif r.change_type == "DELETE":
            short_orig = (r.original_text[:80] + "…") if len(r.original_text) > 80 else r.original_text
            change_summary = f"DELETE: {short_orig}"
        # Escape pipes
        change_summary = change_summary.replace("|", "\\|")
        rationale = r.rationale.replace("|", "\\|")
        rows.append(
            f"| {i} | {r.clause_id} | {r.category.value} | {r.severity.value} | "
            f"{change_summary} | {rationale} |"
        )
    return "\n".join(rows)


def _iteration_timeline(state: GraphState) -> str:
    if not state.iteration_history:
        return "_No iterations recorded._"
    rows = []
    for rec in state.iteration_history:
        v = rec.critic_verdict
        verdict_str = "—"
        if v:
            verdict_str = f"{'✅ approved' if v.approved else '❌ not approved'} ({len(v.issues)} issues, {v.overall_risk.value} risk)"
        rows.append(
            f"- **Iteration {rec.iteration}** ({rec.timestamp.strftime('%H:%M:%S')}) — "
            f"{len(rec.redlines)} redlines · critic verdict: {verdict_str}\n"
            f"  *Strategy:* {rec.drafter_strategy_note or '—'}"
        )
    return "\n".join(rows)


def formatter_node(state: GraphState) -> dict[str, Any]:
    """Builds the final Markdown output and writes it to state.final_output."""
    print(f"[formatter] composing final output (iterations={state.iteration}, approved={state.approved})")

    duration = (datetime.now() - state.started_at).total_seconds()

    md = f"""# ContractLens — Final Review Report

**Status:** {_status_badge(state)}
**Jurisdiction:** {state.jurisdiction.value}
**Iterations run:** {state.iteration} / {state.max_iterations}
**Total redlines:** {len(state.redlines)}
**Wall-clock:** {duration:.1f} s

---

## Executive Summary

{state.critic_verdict.summary if state.critic_verdict else "_(no summary)_"}

---

## Iteration Timeline

{_iteration_timeline(state)}

---

## Checklist Coverage

{_coverage_table(state)}

---

## Final Contract (Marked-Up)

```
{state.current_draft}
```

---

## Redline Rationale

{_redline_table(state)}

---

*Generated by ContractLens · Reflection-Loop Architecture · LangGraph*
"""

    return {"final_output": md}
